consumerKey: 
consumerSecret: 
accessToken: 
accessTokenSecret: 

stream_config:
  - kafka_topic: tweets
    twitter_keywords:
      - duyet
      - duyet.net
      - realDonaldTrump
      - fossil
      - trump
      - vietnam
  - kafka_topic: uit
    twitter_keywords:
      - "#uit"
  - kafka_topic: fossil
    twitter_keywords:
      - "#fossil"
