consumerKey: O0QnK3JsCXjLja4Tbk9h2NpWD
consumerSecret: IjM46sq1rQq5FTiBHloKT39zOukVj34UskTgX4UEGoPZboluSs
accessToken: 387030244-68bVpZQ2x5vninJVvhpGBRki6iqbzEHDjOY2XssE
accessTokenSecret: nfFxT4ak94YNrVz6SEk9TnXiXwyJYMBIRSpTXAeuCLSfk

stream_config:
  - kafka_topic: tweets
    twitter_keywords:
      - duyet
      - duyet.net
      - realDonaldTrump
      - fossil
      - trump
      - vietnam
  - kafka_topic: uit
    twitter_keywords:
      - "#uit"
  - kafka_topic: fossil
    twitter_keywords:
      - "#fossil"
